repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.2.0"  # Updated to the correct format
    hooks:
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: "22.3.0"  # Updated to the correct latest version
    hooks:
      - id: black
        language_version: python3.11  # Ensure it uses Python 3.11

  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"  # Correct format
    hooks:
      - id: flake8
        additional_dependencies: ['flake8==5.0.4']
