services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - trade_network

  celery_worker:
    build: .
    container_name: celery_worker
    entrypoint: ["/app/Executor/Scripts/CeleryScripts/entrypoint.sh"]
    command: celery -A Executor.Scripts.CeleryScripts.V1_poetry_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDBEAT_REDIS_URL=redis://redis:6379/1
      - REDBEAT_REDIS_OPTIONS='{"host":"redis","port":6379,"db":1}'
    env_file:
      - trademan.env
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - trade_network

  celery_beat:
    build: .
    container_name: celery_beat
    entrypoint: ["/app/Executor/Scripts/CeleryScripts/entrypoint.sh"]
    command: celery -A Executor.Scripts.CeleryScripts.V1_poetry_app beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDBEAT_REDIS_URL=redis://redis:6379/1
      - REDBEAT_REDIS_OPTIONS='{"host":"redis","port":6379,"db":1}'
    env_file:
      - trademan.env
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - trade_network

volumes:
  redis_data:

networks:
  trade_network:
    driver: bridge
