services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - trade_network

  celery_worker:
    build: .
    container_name: celery_worker
    entrypoint: ["/app/Executor/Scripts/CeleryScripts/entrypoint.sh"]
    command: celery -A Executor.Scripts.CeleryScripts.V1_poetry_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDBEAT_REDIS_URL=redis://redis:6379/1
      - REDBEAT_REDIS_OPTIONS='{"host":"redis","port":6379,"db":1}'
    env_file:
      - trademan.env
    depends_on:
      - redis
    volumes:
      - .:/app
      - app_data:/app/Data
      - app_sample_data:/app/SampleData
      - trademan_db_data:/app/Data/TradeManDB
      - trademan_signals_data:/app/Data/TradeManDB/Signals
    restart: unless-stopped
    networks:
      - trade_network

  celery_beat:
    build: .
    container_name: celery_beat
    entrypoint: ["/app/Executor/Scripts/CeleryScripts/entrypoint.sh"]
    command: celery -A Executor.Scripts.CeleryScripts.V1_poetry_app beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDBEAT_REDIS_URL=redis://redis:6379/1
      - REDBEAT_REDIS_OPTIONS='{"host":"redis","port":6379,"db":1}'
    env_file:
      - trademan.env
    depends_on:
      - redis
    volumes:
      - .:/app
      - app_data:/app/Data
      - app_sample_data:/app/SampleData
      - trademan_db_data:/app/Data/TradeManDB
      - trademan_signals_data:/app/Data/TradeManDB/Signals
    restart: unless-stopped
    networks:
      - trade_network

  fastapi:
    build: .
    container_name: fastapi
    command: uvicorn User.UserApi.main:app_fastapi --host 0.0.0.0 --port 8082 --reload
    ports:
      - "8082:8082"
    environment:
      - PYTHONPATH=/app
    env_file:
      - trademan.env
    volumes:
      - .:/app
      - app_data:/app/Data
      - app_sample_data:/app/SampleData
      - trademan_db_data:/app/Data/TradeManDB
      - trademan_signals_data:/app/Data/TradeManDB/Signals
    networks:
      - trade_network

volumes:
  redis_data:
  app_data:
  app_sample_data:
  trademan_db_data:
  trademan_signals_data:

networks:
  trade_network:
    driver: bridge
