version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --bind 0.0.0.0
    networks:
      - app_network

  fastapi:
    build: .
    command: python User/UserApi/main.py
    volumes:
      - .:/app
      - ./Data/Logs:/app/Data/Logs
    ports:
      - "8082:8082"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DOCKER_ENV=true
    env_file:
      - trademan.env
    depends_on:
      - redis
    networks:
      - app_network
    working_dir: /app

  celery_worker:
    build: .
    command: celery -A Executor.Scripts.CeleryScripts.V1_poetry_app worker --loglevel=INFO -P solo
    volumes:
      - .:/app
      - ./Data/Logs:/app/Data/Logs
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DOCKER_ENV=true
      - C_FORCE_ROOT=true
    env_file:
      - trademan.env
    depends_on:
      - redis
    networks:
      - app_network
    working_dir: /app

  celery_beat:
    build: .
    command: celery -A Executor.Scripts.CeleryScripts.V1_poetry_app beat --loglevel=INFO
    volumes:
      - .:/app
      - ./Data/Logs:/app/Data/Logs
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DOCKER_ENV=true
      - C_FORCE_ROOT=true
    env_file:
      - trademan.env
    depends_on:
      - redis
      - celery_worker
    networks:
      - app_network
    working_dir: /app

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
