"""Initial migration

Revision ID: 5501f4d194dd
Revises: 
Create Date: 2024-09-06 10:51:59.671573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5501f4d194dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_trades',
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('hedge_entry_price', sa.Float(), nullable=True),
    sa.Column('hedge_exit_price', sa.Float(), nullable=True),
    sa.Column('trade_points', sa.Float(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('net_pnl', sa.Float(), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('trading_symbol', sa.String(), nullable=False),
    sa.Column('signal', sa.String(), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_table('holdings',
    sa.Column('hedge_entry_price', sa.Float(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('margin_utilised', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('setup', sa.Float(), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('trading_symbol', sa.String(), nullable=False),
    sa.Column('signal', sa.String(), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_table('signals',
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('hedge_entry_price', sa.Float(), nullable=True),
    sa.Column('hedge_exit_price', sa.Float(), nullable=True),
    sa.Column('trade_points', sa.Float(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('trading_symbol', sa.String(), nullable=False),
    sa.Column('signal', sa.String(), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('trade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signals')
    op.drop_table('holdings')
    op.drop_table('completed_trades')
    # ### end Alembic commands ###
