name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Decode and save Firebase credentials
      run: |
        echo ${{ secrets.FIREBASE_CRED_PATH }} | base64 -d > $GITHUB_WORKSPACE/firebase_credentials.json
      shell: bash

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install firebase-admin

    - name: Set environment variables
      run: |
        echo "FIREBASE_CRED_PATH=$GITHUB_WORKSPACE/firebase_credentials.json" >> $GITHUB_ENV
        echo "FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}" >> $GITHUB_ENV

    - name: Run Firebase script
      env:
        FIREBASE_CRED_PATH: ${{ env.FIREBASE_CRED_PATH }}
        FIREBASE_DATABASE_URL: ${{ env.FIREBASE_DATABASE_URL }}
      run: |
        pip install pytest
        pytest --tb=short -v
