name: Python application CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Firebase Credentials File
      run: |
        #!/bin/bash
        cat <<EOF >firebase_credentials.json
        ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
        EOF
      env:
        FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}

    - name: Check Firebase Credentials File
      run: cat ./firebase_credentials.json


    - name: Load environment variables
      run: |
        echo "FIREBASE_URL=${{ secrets.FIREBASE_URL }}" >> $GITHUB_ENV
        echo "FIREBASE_CREDENTIALS_PATH=./firebase_credentials.json" >> $GITHUB_ENV

    - name: Check formatting with black
      run: |
        pip install black
        black .

    # Uncomment and use as needed:
    # - name: Lint with flake8
    #   run: |
    #     pip install flake8
    #     flake8 .

    # - name: Check documentation with pydocstyle
    #   run: |
    #     pip install pydocstyle
    #     pydocstyle .

    - name: Test with pytest
      run: |
        pip install pytest
        pytest
