name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Firebase credentials
      # Write the JSON content from the secret to a file
      run: echo "${{ secrets.FIREBASE_CRED_PATH }}" > firebase-service-account.json
      shell: bash

    - name: Export Firebase environment variables
      # Set the environment variables for the database URL and credentials path
      run: |
        echo "FIREBASE_CRED_PATH=$(pwd)/firebase-service-account.json" >> $GITHUB_ENV
        echo "FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}" >> $GITHUB_ENV
      shell: bash

    - name: Verify Firebase credentials
      run: |
        if [ -f "$FIREBASE_CRED_PATH" ]; then
          echo "Firebase credentials file found at $FIREBASE_CRED_PATH"
          cat $FIREBASE_CRED_PATH
        else
          echo "Firebase credentials file not found."
          exit 1
        fi
      shell: bash

    - name: Check formatting with black
      run: |
        pip install black
        black .

    - name: Test with pytest
      env:
        FIREBASE_CRED_PATH: ${{ env.FIREBASE_CRED_PATH }}
        FIREBASE_DATABASE_URL: ${{ env.FIREBASE_DATABASE_URL }}
      run: |
        pip install pytest
        pytest



    # - name: Lint with flake8
    #   run: |
    #     pip install flake8
    #     flake8 .

    # - name: Check documentation with pydocstyle
    #   run: |
    #     pip install pydocstyle
    #     pydocstyle .

